spring:
  application:
    name: Guarantrr-Payment
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=Test;
#    url: jdbc:jdbc:sqlserver://172.17.0.2:1433;databaseName=Test;
    username: sa
    password: SaUser123456



